Repository MSRudolph/PauliPropagation.jl, pull requests merged in 2025-04, with the labels that each got.

#73 Rework Pauli integer types
  src/PauliAlgebra/PauliAlgebra.jl
  src/PauliAlgebra/bitoperations.jl
  test/test_datatypes.jl
Labels: enhancement, performance

#75 Setup doc CI
  .github/workflows/documentation.yml
  docs/Project.toml
  docs/make.jl
  docs/src/assets/logo.png
  docs/src/index.md
  docs/src/installation.md
  docs/src/introduction.md
  docs/src/tutorials.md
Labels: enhancement

#76 scaffolded doc
  .github/workflows/documentation.yml
  docs/Project.toml
  docs/make.jl
  docs/src/api/Circuits.md
  docs/src/api/Gates.md
  docs/src/api/NumericalCertificates.md
  docs/src/api/PathProperties.md
  docs/src/api/PauliAlgebra.md
  docs/src/api/PauliTransferMatrix.md
  docs/src/api/Propagation.md
  docs/src/api/StateOverlap.md
  docs/src/api/Surrogate.md
  docs/src/api/Truncations.md
  docs/src/assets/logo.png
  docs/src/index.md
  docs/src/installation.md
  docs/src/tutorials.md
Labels: documentation
